<?php
/**
 * Entry point "blocks" script registration and enqueue.
 *
 * This file will be copied to the assets output directory
 * with Webpack using wp-scripts build. The build command must
 * be run before this file will be available.
 *
 * This file must be included from the build output directory in a project.
 * and will be loaded from there.
 *
 * @package wp-newsletter-builder
 */

defined( 'ABSPATH' ) || exit;

/**
 * Enqueues the blocks stylesheet.
 */
function wp_newsletter_builder_register_blocks_scripts(): void {
	/**
	 * Asset file generated by wp-scripts.
	 *
	 * @var array{dependencies: string[], version: string}|false $asset_file
	 */
	$asset_file = include __DIR__ . '/index.asset.php';

	if ( ! $asset_file ) {
		return;
	}

	// Register the blocks style.
	wp_register_style(
		'wp-newsletter-builder-blocks-css',
		plugins_url( 'index.css', __FILE__ ),
		[],
		$asset_file['version'],
	);
}
add_action( 'init', 'wp_newsletter_builder_register_blocks_scripts' );

/**
 * Enqueue styles for the blocks entry point.
 */
function wp_newsletter_builder_enqueue_blocks_styles(): void {
	wp_enqueue_style( 'wp-newsletter-builder-blocks-css' );
}
add_action( 'wp_enqueue_scripts', 'wp_newsletter_builder_enqueue_blocks_styles' );
