<?php
/**
 * Entry point "editor" script registration and enqueue.
 *
 * This file will be copied to the assets output directory
 * with Webpack using wp-scripts build. The build command must
 * be run before this file will be available.
 *
 * This file must be included from the build output directory in a project.
 * and will be loaded from there.
 *
 * @package wp-newsletter-builder
 */

/**
 * Register the editor entry point assets so that they can be enqueued.
 */
function wp_newsletter_builder_register_editor_scripts(): void {
	/**
	 * Asset file generated by wp-scripts.
	 *
	 * @var array{dependencies: string[], version: string}|false $asset_file
	 */
	$asset_file = include __DIR__ . '/index.asset.php';

	if ( ! $asset_file ) {
		return;
	}

	// Register the editor style.
	wp_register_style(
		'wp-newsletter-builder-editor-css',
		plugins_url( 'index.css', __FILE__ ),
		[],
		$asset_file['version'],
	);
}
add_action( 'init', 'wp_newsletter_builder_register_editor_scripts' );

/**
 * Enqueue styles for the editor entry point.
 */
function wp_newsletter_builder_enqueue_editor_styles(): void {
	global $post_type;

	// Only enqueue the styles for our specific post types.
	if ( 'nb_newsletter' === $post_type || 'nb_template' === $post_type ) {
		wp_enqueue_style( 'wp-newsletter-builder-editor-css' );
	}
}
add_action( 'enqueue_block_editor_assets', 'wp_newsletter_builder_enqueue_editor_styles' );
